---
title: "EP5_hw"
author: "Vincent Fischer"
date: '2022-03-29'
output: html_document
---
## loading libaries
```{r}

suppressPackageStartupMessages({
  library(AnnotationHub)
  library(ensembldb)
  library(GenomicRanges)
  library(epiwraps)
  library(rtracklayer)
  library(ggplot2)
  library(magick)
})
ah <- AnnotationHub(localHub=TRUE)
ensdb <- ah[["AH89211"]]

```

## download peaks for H3K4me3 and H3K27me3

```{r, eval=FALSE}
dir.create("peaks")
dir.create("tracks")
options(timeout=1800)

# H3K27me3
download.file("https://www.encodeproject.org/files/ENCFF008XKX/@@download/ENCFF008XKX.bed.gz", "peaks/H3K27me3.bed.gz")
download.file("https://www.encodeproject.org/files/ENCFF160FEV/@@download/ENCFF160FEV.bigWig", "tracks/H3K27me3.bw")


# H3K4me3
download.file("https://www.encodeproject.org/files/ENCFF247GVM/@@download/ENCFF247GVM.bed.gz", "peaks/H3K4me3.bed.gz")
download.file("https://www.encodeproject.org/files/ENCFF611GSQ/@@download/ENCFF611GSQ.bigWig", "tracks/H3K4me3.bw")
```

## Reading in the data

```{r}
k4me3 <- import("peaks/H3K4me3.bed.gz", format="NarrowPeak")
k27me3 <- import("peaks/H3K27me3.bed.gz", format="NarrowPeak")
```

## Overlaps

```{r}
sum(overlapsAny(k4me3,k27me3))
k4k27peaks <- k4me3[overlapsAny(k4me3,k27me3)]
length(k4k27peaks)
```
3219 overlaps/ bivalent regions between k4m3 and k27me3
```{r}
listOfpeaks <- list(k4me3=k4me3, k27me3 = k27me3)
#listOfpeaks
#regionOverlaps(listOfpeaks) doesnt work
regionUpset(listOfpeaks)
```

### 2746 overlaps according to function regionUpset

## download peaks for megakaryocyte H3K4me3 and H3K27me3

```{r, eval=FALSE}

# megaH3K27me3
download.file("https://www.encodeproject.org/files/ENCFF026IPZ//@@download/ENCFF026IPZ.bed.gz", "peaks/megaH3K27me3.bed.gz")



# megaH3K4me3 
download.file("https://www.encodeproject.org/files/ENCFF661TZV//@@download/ENCFF661TZV.bed.gz", "peaks/megaH3K4me3.bed.gz")

```
## Reading in the mega data

```{r}
megak4me3 <- import("peaks/megaH3K4me3.bed.gz", format="NarrowPeak")
megak27me3 <- import("peaks/megaH3K27me3.bed.gz", format="NarrowPeak")
```
## comparing peaks of esc and mega data

```{r}

listOfmegapeaks <- list( megak4me3 = megak4me3, megak27me3 = megak27me3, k4me3=k4me3, k27me3 = k27me3  )
#listOfpeaks
#regionOverlaps(listOfpeaks) doesnt work
regionUpset(listOfmegapeaks)
regionUpset(listOfmegapeaks, reference = c(megak27me3,megak4me3))
length(k4me3)
length(k27me3)
length(megak4me3)
length(megak27me3)

```
```{r}
# difference between overlapping peaks depending on peak list (esc vs esc+megakaryocyte) and reference (no reference vs mega)
```

## SessionInfo
```{r}
sessionInfo()
```

